#!/usr/bin/env python

from __future__ import with_statement, print_function
import os
import re
import subprocess
import sys

ignore_codes = ["E501"]


def system(*args, **kwargs):
    kwargs.setdefault('stdout', subprocess.PIPE)
    kwargs.setdefault('stderr', subprocess.STDOUT)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return out


def main():
    modified = re.compile('^\s*[AM]+\s+(?P<name>.*\.py)', re.MULTILINE)
    files = system('git', 'diff', '--cached', '--name-status').decode("utf-8")
    files = modified.findall(files)

    count = 0
    for changed_file in files:
        print('Checking: ' + changed_file)
        output = system('pep8', '--ignore', ','.join(ignore_codes), '--count', changed_file)
        output = output.splitlines()
        count += int(output.pop())
        output.append('')
        print('\n'.join(output))

    with open(sys.argv[1], 'a') as commit_message:
        print('\npep8 errors: ' + str(count) + '\n', file=commit_message)


if __name__ == '__main__':
    main()
